### ISSUE TITLE
How to Use This tool,

### ISSUE THREAD

**Issue by Daringbaaz** [ouwou/telegram-protected-bypass#1]
Hello, Can You Please tell me how to use this on Windows?

Where is Installer for Windows.

**Comment by lalrochhara** [comment]
> Hello, Can You Please tell me how to use this on Windows?
> 
> Where is Installer for Windows.

Same question here 🥺

**Comment by TaoPanfeng** [comment]
> 

me too

**Comment by ouwou** [comment]
inject the dll. i added a download

**Comment by Daringbaaz** [comment]
> inject the dll. i added a download

Where to inject the DLL file on windows, please write clear instructions and path for injecting the file

"telegram-protected-bypass.dll" I Belive the filename needed to be raname or placed on specific path to overwrite the default config and we need the correct instructions

Thanks
